# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 02:03
from __future__ import unicode_literals

import apps.goods.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(0, '男'), (1, '女'), (None, '隐藏')], default=None, max_length=4, null=True, validators=[apps.goods.validator.valid_sex], verbose_name='性别'),
        ),
    ]
