# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 02:08
from __future__ import unicode_literals

import apps.goods.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190823_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '隐藏')], null=True, validators=[apps.goods.validator.valid_sex], verbose_name='性别'),
        ),
    ]
