# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190822_1728'),
        ('accounts', '0003_auto_20190823_1008'),
    ]

    operations = [
    ]
