# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_name', to='goods.Goods', verbose_name='出租物品')),
                ('lee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lee', to=settings.AUTH_USER_MODEL, verbose_name='承租人')),
                ('lor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lor', to=settings.AUTH_USER_MODEL, verbose_name='出租人')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='goods.Goods', verbose_name='租金')),
            ],
            options={
                'verbose_name': '租赁记录',
                'verbose_name_plural': '租赁记录',
            },
        ),
    ]
